In [19]:
import pandas as pd
import numpy as np
import re

In [8]:
df = pd.read_csv('finance_liquor_sales.csv', parse_dates = ["date"])

In [43]:
df.head()

,invoice_and_item_number,date,store_number,store_name,address,city,zip_code,store_location,county_number,county,...,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,volume_sold_liters,volume_sold_gallons,longitude,latitude
0,INV-31797900035,2020-11-10,4967,Jeffs Market / Blue Grass,"102, W Mayne St",Blue Grass,52726,POINT (-90.766126 41.509119),82,SCOTT,...,12,375,9.99,14.99,1,14.99,0.37,0.09,-90.766126,41.509119
1,INV-23548800092,2019-11-27,2601,Hy-Vee Food Store / Fairfield,1300 West Burlington Ave,Fairfield,52556,POINT (-91.978702 41.006456),51,JEFFERSON,...,12,1000,2.42,3.63,6,21.78,6.00,1.58,-91.978702,41.006456
2,INV-23609300026,2019-12-02,4962,Hilltop Grocery,1312 Harrison St,Davenport,52803,NaN,82,SCOTT,...,24,375,4.20,6.30,3,18.90,1.12,0.29,NaN,NaN
3,INV-39482900037,2021-08-24,3719,Wal-Mart 0581 / Marshalltown,2802 S Center St,Marshalltown,50158,POINT (-92.91231 42.012918),64,MARSHALL,...,12,20,4.93,7.40,12,88.80,0.24,0.06,-92.912310,42.012918
4,INV-39520400088,2021-08-25,5423,Stammer Liquor Corp,615 2nd Ave,Sheldon,51201,POINT (-95.854899 43.184242),71,OBRIEN,...,12,1000,4.85,7.28,4,29.12,4.00,1.05,-95.854899,43.184242

In [36]:
def get_lon(point):
    if pd.isna(point):
        return np.nan
    return re.findall('POINT \((.+) .+\)', point)[0]

In [39]:
def get_lat(point):
    if pd.isna(point):
        return np.nan
    return re.findall('POINT \(.+ (.+)\)', point)[0]

In [41]:
df['longitude'] = df['store_location'].apply(get_lon).astype(float)
df['latitude'] = df['store_location'].apply(get_lat).astype(float)

In [44]:
df.to_csv('finance_liquor_sales_final.csv')